name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [ 21.x ]
    steps:
        - uses: actions/checkout@v4
        - name: Starting Node.js ${{matrix.node-version}}
          uses: actions/setup-node@v4
          with: 
            node-version: ${{ matrix.node-version}}
        - name: install modules
          working-directory: ./packages/client
          run: npm install
        - name: build project
          working-directory: ./packages/client
          run: npm run build
        - name: unit test
          working-directory: ./packages/client
          run: npm run test
        - name: e2e test
          working-directory: ./packages/client
          run: npm run test:e2e
        - name: storybook test
          working-directory: ./packages/client
          run: npm run build-storybook